version: 0.2

phases:
    install:
        runtime-versions:
          python: 3.8
        commands:
            - echo "Installing ... "
            - apt install python3-pip 
            - pip3 install gunicorn
            - pip3 install -r requirements.txt 

    build:
        commands:
            - echo "Deploying ..."
            - gunicorn --workers=4 --bind=0.0.0.0:5000 app:app
